name: aurabeat
description: "A comprehensive Flutter music application with AI generation, remixing, and audio processing capabilities."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  just_audio: ^0.9.36
  audio_waveforms: ^1.0.5
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0
  path_provider: ^2.1.2
  go_router: ^12.1.3
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true